services:
  mongo_db_data:
    image: mongo:latest
    container_name: mongo_db_data
    ports:
      - "27020:27017"
    volumes:
      - mongo_db_data:/data/db
    restart: always
    hostname: mongo_db_data

volumes:
  mongo_db_data: